### PR TITLE
Update README to include Rails Instructions

### PR DESCRIPTION
**Pull request by joshhepworth**

### CODE REVIEW

**Comment by dwbutler** [comment]
The best solution is to create `lib/sailthru-client.rb` which just has `require 'sailthru'`.

**Comment by BenMorganIO** [comment]
@dwbutler I don't think that's the standard methodology. There could be an update inside of the source requiring it automatically if the `Rails` module is defined.

**Comment by dwbutler** [comment]
This isn't actually a Rails issue. It's an issue with how Bundler automatically requires gems specified in the Gemfile when running `Bundler.require`.

Your gem is named `sailthru-client`. By [convention](http://guides.rubygems.org/name-your-gem/), the corresponding require statement should be `require 'sailthru/client'`. When Bundler sees `gem 'sailthru-client'` in the Gemfile, it will attempt to require it with the standard naming convention and silently fail, causing the gem to not be loaded into the application automatically.

The "nice" way around this, which doesn't force users of the gem to add a special `require` statement to their Gemfile, is to simply create a `lib/sailthru-client.rb` file which then requires the correct stuff. This is standard practice. Many gems do this.

**Comment by BenMorganIO** [comment]
@dwbutler I was under the impression that the solution was for a users rails application. This would be a great solution.

**Comment by lindsayneubauer** [comment]
@joshhepworth @dwbutler @vjustov Just merged @vjustov solution. Please verify that this fix works. If so, can we close out this PR. If not, please give me more details on the issue.

**Comment by dwbutler** [comment]
Thanks, I believe this will do the trick!

**Pull request closed without merging**
